name: Fracture Detection

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: Install dependencies
      run: pip install -r requirements.txt
        
    - name: Train Model
      run: python train_model.py
      
  detect:
    needs: train
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: Install dependencies
      run: pip install -r requirements.txt
        
    - name: Detect Fracture
      run: python detect_fracture.py
